version: "3.8"


#depends_on:
#  translation:
#    condition: service_healthy

services:
  transcription:
    container_name: transcription
    hostname: transcription
    networks:
      - backnet
    build:
      context: ./transcription
      dockerfile: Dockerfile
    image: translator-transcription
    ports:
      - "2700:2700"
    restart: on-failure
    environment:
      - TRANSCRIPTION_DEBUGMODE=True
      - TRANSLATION_DOMAIN=translation:5000
      - TRANSCRIPTION_PORT=2700
      - VOSK_MODEL_PATHS={"en":"models/vosk-model-en-us-0.22","de":"models/vosk-model-de-0.21"}


  translation:
    container_name: translation
    hostname: translation
    networks:
      - backnet
    #build:
    #  context: ./translation
    #  dockerfile: Dockerfile
    #image: translator-translation
    build:
      context: ./translation
      dockerfile: Dockerfile
    image: translator-translation
    ports:
      - "5000:5000"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]
      interval: 3s
      timeout: 5s
      retries: 1
      start_period: 0s
      start_interval: 5s
    environment:
      - LT_DISABLE_FILES_TRANSLATION=true
      - LT_DISABLE_WEB_UI=true
      - LT_UPDATE_MODELS=true
      - LT_HOST=0.0.0.0
      - LT_LOAD_ONLY=en,de
      - LT_DEBUG=true
    #  - TRANSCRIPTION_DEBUGMODE=False

networks:
  backnet:
    name: backnet


