server:
  port: 8081

spring:
  datasource:
    leader:
      url: jdbc:postgresql://localhost:6543/textdb_leader
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
    follower:
      url: jdbc:postgresql://localhost:6544/textdb_follower
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver