version: '3.8'

services:
  # UserServiceDB
  user_service_db:
    build:
      context: ./Dockerimages/UserDBImage
      dockerfile: Dockerfile
    container_name: UserServiceDB
    networks:
      - UserServiceNetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # UserService
  user_service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: UserService
    networks:
      - UserServiceNetwork
    depends_on:
      user_service_db:
        condition: service_healthy

  # TextServiceDB Leader
  text_service_db_leader:
    build:
      context: Dockerimages/TextDBImage/Leader
      dockerfile: Leader.Dockerfile
    ports:
      - "6543:6543"
    container_name: TextServiceDBLeader
    networks:
      - TextServiceNetwork
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # TextServiceDB Follower
  text_service_db_follower:
    build:
      context: Dockerimages/TextDBImage/Follower
      dockerfile: Follower.Dockerfile
    container_name: TextServiceDBFollower
    ports:
      - "6544:6544"
    networks:
      - TextServiceNetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all"]
    depends_on:
      text_service_db_leader:
        condition: service_healthy

  # TextServiceLeader
  text_service_leader:
    build:
      context: ./TextServiceLeader
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: TextServiceLeader
    networks:
      - TextServiceNetwork
    depends_on:
      text_service_db_leader:
        condition: service_healthy

  # TextServiceFollower
  text_service_follower:
    build:
      context: ./TextServiceFollower
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: TextServiceFollower
    networks:
      - TextServiceNetwork
    depends_on:
      text_service_db_follower:
        condition: service_healthy

  text_service_gateway:
    build:
      context: ./TextServiceGateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: TextServiceGateway
    networks:
      - TextServiceNetwork
    depends_on:
      - text_service_follower

networks:
  UserServiceNetwork:
    driver: bridge
  TextServiceNetwork:
    driver: bridge