server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://text-db-leader:6543/textdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: transcription-rabbitmq
    port: 5672
    username: guest
    password: guest