server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://TextServiceDBLeader:6543/textdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: transcription_rabbitmq
    port: 5672
    username: guest
    password: guest